name : Test_WorkFlow_File
on: push
jobs:
    First_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Welcome Message
              run: echo "Welcome To GitHub Actions Jobs"

            - name: List and Read files
              run: |
               ls -lh
               cat README.md
               cowsay -f lion "Run for your life, man; I am a lion....Roar >> cowsaylion.txt"

           #- name: List files
           #  run: ls -lh

           #- name: Read files
           #  run: cat README.md