name : Test_WorkFlow_File
on: push
jobs:
    First_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Welcome Message
              run: echo "Welcome To GitHub Actions Jobs"

            - name: List files
              run: ls -lh

            - name: Read files
              run: cat README.md