name: Generate ASCII Artwork With Script

on: push

jobs: 
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List Repo Files
        run: ls -lh

      - name: Execute shell script
        run: |
            chmod +x ./ascii-script.shell:
            ./ascii-script.sh

      - name: List Files Again
        run: ls -lhtra