name : Test WorkFlow File
on: push
jobs:
    First_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Welcome Message
              run: echo "Welcome To GitHub Actions Jobs"

            - name: Create, List, and Read files
              run: |
               touch cowsayfile.txt
               ls -lh
               cat README.md

            - name: Generate ASCII Artwork
              run: cowsay -f dragon "Run for your life, man; I am a dragon....Roar" >> cowsayfile.txt

           #- name: List files
           #  run: ls -lh

           #- name: Read files
           #  run: cat README.md