#===============================================================================================
# WorkFlow WITHOUT Use of Environment Variables And Secrets
#===============================================================================================

# name: Exploring Variables And Secrets

# on: push

# jobs:
#     docker:
#         runs-on: ubuntu-lates
#         steps:
#             - name: Docker Build
#               run: docker build -t docker.io/dockerUsername/imageName:latest
              
#             - name: Docker Login
#               run: docker login --username=dockerUsername --password=s3cUrePaSsw0rd

#             - name: Docker Publish
#               run: docker push docker.io/dockerusername/imageName:latest

#     deploy:
#         needs: docker
#         runs-on: ubuntu-latest
#         steps:
#             - name: Docker Run
#               run: docker run -d -p 8080:80 docker.io/dockerUsername/imageName:latest


#===================================================================================================
# WorkFlow WITH The Use of Environment Variables And Secrets At The STEP Level
# Environment Variables Can Be Added Both At Job-level and Step-level
#===================================================================================================

# name: Exploring Variables And Secrets

# on: push

# jobs:
#     docker:
#         runs-on: ubuntu-lates
#         steps:
#             - name: Docker Build
#               env:
#                 CONTAINER_REGISTRY: docker.io
#                 DOCKER_USERNAME: ariyomichael
#                 IMAGENAME: learning-github-actions
#             # Environment variables can be referenced using either $Variablename or ${{VariableName}} formats
#               run: docker build -t $CONTAINER_REGISTRY/${{env.DOCKER_USERNAME}}/$IMAGENAME:latest
              
#             - name: Docker Login
#               env:
#                 DOCKER_PASSWORD: Amcb@3030
#                 DOCKER_USERNAME: ariyomichael
#               run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

#             - name: Docker Publish
#               env:
#                 CONTAINER_REGISTRY: docker.io
#                 DOCKER_USERNAME: ariyomichael
#                 IMAGENAME: learning-github-actions
#               run: docker push ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGENAME}}:latest

#     deploy:
#         needs: docker
#         runs-on: ubuntu-latest
#         steps:
#             - name: Docker Run
#               env:
#                 CONTAINER_REGISTRY: docker.io
#                 DOCKER_USERNAME: ariyomichael
#                 IMAGENAME: learning-github-actions
#               run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGENAME:latest

    
#===================================================================================================
# WorkFlow WITH The Use of Environment Variables And Secrets At The JOB level
#==================================================================================================

# name: Exploring Variables And Secrets

# on: push

# jobs:
#     docker:
#         env:
#             CONTAINER_REGISTRY: docker.io
#             DOCKER_USERNAME: ariyomichael
#             IMAGENAME: learning-github-actions
#         runs-on: ubuntu-lates
#         steps:
#             - name: Docker Build
#               run: docker build -t $CONTAINER_REGISTRY/${{env.DOCKER_USERNAME}}/$IMAGENAME:latest
              
#             - name: Docker Login
#               env:
#                 DOCKER_PASSWORD: Amcb@3030
#               run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

#             - name: Docker Publish
#               run: docker push ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGENAME}}:latest

#     deploy:
#         env:
#             CONTAINER_REGISTRY: docker.io
#             DOCKER_USERNAME: ariyomichael
#             IMAGENAME: learning-github-actions
#         needs: docker
#         runs-on: ubuntu-latest
#         steps:
#             - name: Docker Run
#               run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGENAME:latest

#=====================================================================================================
# WorkFlow WITH The Use of Environment Variables And Secrets At The WORKFLOW level
#=====================================================================================================

name: Exploring Variables And Secrets

on: workflow_dispatch
    #push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: ariyomichael
    IMAGENAME: learning-github-actions
              
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          run: echo docker build -t $CONTAINER_REGISTRY/${{env.DOCKER_USERNAME}}/$IMAGENAME:latest
                            
        - name: Docker Login
          env:
            DOCKER_PASSWORD: Amcb@3030
          run: echo docker login --username=$DOCKER_USERNAME --password=${{secrets.DOCKER_PASSWORD}}
              
        - name: Docker Publish
          run: echo docker push ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGENAME}}:latest
              
    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
        - name: Docker Run
          run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGENAME:latest
              
              
