name: Exploring Workflow Triggers, Filters, And Activities

on:
    workflow_dispatch:
#    schedule:
#        - cron: "*/59 * * * *"
    push: 
        branches:
            - main
            - '!feature/*' #ignoring branches that starts with feature/* using the ! ('Not' symbol)
#        branches-ignore:
#            - feature/*    #feature/add-music, feature/updateImages, etc
#            - test/**      #test/ui/index, test/checout/payment/, etc.
    pull_request:
        types:
            - opened
            - closed
        paths-ignore:   #workflow will run only on pull-requests involving other to changes to files asides README.md file
            - README.md
        branches:
            - main      # configures workflow to run on pull-requests targeting specific branches   

jobs:
    Say-Hello:
        runs-on: ubuntu-latest
        steps:
            - name: Workflow Event Type
              run: echo This workflow/job is executed for the event type ${{github.event_name}}
